function AnioBisiesto(a) { return 0 == a % 4 && 0 != a % 100 || 0 == a % 400 ? 1 : 0 } function esDigito(a) { a = a.charCodeAt(0); return 47 < a && 58 > a } function valSep(a) { var b; return b = (b = "-" == a.value.charAt(2) && "-" == a.value.charAt(5)) || "/" == a.value.charAt(2) && "/" == a.value.charAt(5) }
function finMes(a) { var b = parseInt(a.value.substr(3, 2), 10), a = parseInt(a.value.substr(6, 4), 10), c = 0; switch (b) { case 1: c = 31; break; case 2: c = AnioBisiesto(a) ? 29 : 28; break; case 3: c = 31; break; case 4: c = 30; break; case 5: c = 31; break; case 6: c = 30; break; case 7: c = 31; break; case 8: c = 31; break; case 9: c = 30; break; case 10: c = 31; break; case 11: c = 30; break; case 12: c = 31 } return c } function valDia(a) { var b = !1, c = parseInt(a.value.substr(0, 2), 10); return b = b || 1 <= c && c <= finMes(a) }
function valMes(a) { var b = !1, a = parseInt(a.value.substr(3, 2), 10); return b || 1 <= a && 12 >= a } function valAno(a) { var b = !0, a = a.value.substr(6); if (b = b && (2 == a.length || 4 == a.length)) for (var c = 0; c < a.length; c++) b = b && esDigito(a.charAt(c)); 4 == a.length && (b = b && 1900 <= a); return b } function valFecha(a) { var b = !0; "" != a.value && (5 == a.value.length && (a.value = a.value + "/" + (new Date).getFullYear()), b = (b = (b = (b = b && valAno(a)) && valMes(a)) && valDia(a)) && valSep(a), b || (alert("Fecha inv\u00e1lida"), a.value = "", a.focus())) }
function valHora(a) { var b = !0; if ("" != a.value) { var c = parseInt(a.value.substr(0, 2), 10), d = parseInt(a.value.substr(3, 2), 10), b = b && 23 >= c && 59 >= d && 5 == a.value.length; b || (alert("Hora inv\u00e1lida"), a.value = "", a.focus()) } } function valNumero(a) { "" != a.value && !IsNumeric(a.value) && (alert("Ingrese N\u00famero"), a.value = "", a.focus()) } function valNumeroSinPunto(a) { "" != a.value && !IsNumericSinPunto(a.value) && (alert("Ingrese s\u00f3lo n\u00famero (sin puntos)"), a.value = "", a.focus()) }
function IsNumeric(a) { var b = !0, c, d = 0; for (i = 0; i < a.length && !0 == b; i++) c = a.charAt(i), -1 == "0123456789.-".indexOf(c) && (b = !1), "." == c && (d += 1); 1 < d && (b = !1); return b } function IsNumericSinPunto(a) { var b = !0, c; for (i = 0; i < a.length && !0 == b; i++) c = a.charAt(i), -1 == "0123456789".indexOf(c) && (b = !1); return b };
var patron = [2, 2, 4], patron2 = [2, 2];
function mascara(a, c, b, d) {
    if (a.valant != a.value) {
        val = a.value; largo = val.length; val = val.split(c); val2 = ""; for (r = 0; r < val.length; r++) val2 += val[r]; if (d) for (z = 0; z < val2.length; z++)-1 == "0123456789".indexOf(val2.charAt(z)) && (val2 = val2.replace(val2.charAt(z), "")), isNaN(val2.charAt(z)) && (letra = RegExp(val2.charAt(z), "g"), val2 = val2.replace(letra, "")); val = ""; val3 = []; for (s = 0; s < b.length; s++) val3[s] = val2.substring(0, b[s]), val2 = val2.substr(b[s]); for (q = 0; q < val3.length; q++) 0 == q ? val = val3[q] : "" != val3[q] && (val += c + val3[q]);
        a.value = val; a.valant = val
    } 
};