/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AlarmaScreening: Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idalarmascreening; 
        //private Efector m_idefector; 
		private SolicitudScreening m_idsolicitudscreening; 
		private string m_descripcion; 
		private int m_idusuarioregistro; 
		private DateTime m_fecharegistro; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AlarmaScreening()
		{
			m_idalarmascreening = 0; 
            //m_idefector = new Efector(); 
			m_idsolicitudscreening = new SolicitudScreening(); 
			m_descripcion = String.Empty; 
			m_idusuarioregistro = 0; 
			m_fecharegistro = DateTime.MinValue; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public AlarmaScreening(
            //Efector idefector, 
			SolicitudScreening idsolicitudscreening, 
			string descripcion, 
			int idusuarioregistro, 
			DateTime fecharegistro)
			: this()
		{
            //m_idefector = idefector;
			m_idsolicitudscreening = idsolicitudscreening;
			m_descripcion = descripcion;
			m_idusuarioregistro = idusuarioregistro;
			m_fecharegistro = fecharegistro;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdAlarmaScreening
		{
			get { return m_idalarmascreening; }
			set
			{
				m_isChanged |= ( m_idalarmascreening != value ); 
				m_idalarmascreening = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
        //public Efector IdEfector
        //{
        //    get { return m_idefector; }
        //    set
        //    {
        //        m_isChanged |= ( m_idefector != value ); 
        //        m_idefector = value;
        //    }

        //}
			
		/// <summary>
		/// 
		/// </summary>
		public SolicitudScreening IdSolicitudScreening
		{
			get { return m_idsolicitudscreening; }
			set
			{
				m_isChanged |= ( m_idsolicitudscreening != value ); 
				m_idsolicitudscreening = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Descripcion
		{
			get { return m_descripcion; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Descripcion", value, "null");
				
				if(  value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for Descripcion", value, value.ToString());
				
				m_isChanged |= (m_descripcion != value); m_descripcion = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public int IdUsuarioRegistro
		{
			get { return m_idusuarioregistro; }
			set
			{
				m_isChanged |= ( m_idusuarioregistro != value ); 
				m_idusuarioregistro = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime FechaRegistro
		{
			get { return m_fecharegistro; }
			set
			{
				m_isChanged |= ( m_fecharegistro != value ); 
				m_fecharegistro = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
