/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Configuracion : Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idconfiguracion; 
		private Efector m_idefector; 
		private int m_nivel; 
		private string m_rutalogo;

        private bool m_principalturno;
        private bool m_principalrecepcion;
        private bool m_principalimpresionht;
        private bool m_principalcargaresultados;
        private bool m_principalvalidacion;
        private bool m_principalimpresionresultados;
        private bool m_principalurgencias;
        private bool m_principalresultados;
        //private string m_nombreimpresora; 

		private string m_encabezadolinea1; 
		private string m_encabezadolinea2; 
		private string m_encabezadolinea3;

        private string m_encabezadolinea1microbiologia;
        private string m_encabezadolinea2microbiologia;
        private string m_encabezadolinea3microbiologia; 

		private int m_tiponumeracionprotocolo;
        private bool m_utilizanumeroeliminado;
		private int m_nroprotocolo;
        private int m_tipocalculodiasretiro;
		private int m_diasretiro; 
        /// <summary>
        private bool m_generacomprobanteprotocolo;
        private string m_textoadicionalcomprobanteprotocolo;
        private bool m_generacomprobanteprotocolomicrobiologia;
        private string m_textoadicionalcomprobanteprotocolomicrobiologia;
        /// </summary>
		
        private bool m_recordarorigenprotocolo;
        private bool m_recordarsectorprotocolo;
        private int m_cantidadprotocolosporpagina ;

        private bool m_modificarprotocoloterminado;
        private bool m_eliminarprotocoloterminado;
		private bool m_turno; 
		private bool m_generacomprobanteturno;
        private bool m_smscancelaturno;
        private int m_tipolistaprotocolo;
        private int m_tipohojatrabajo;
        private int m_tipocargaresultado;
        private bool m_ordencargaresultado;
        private bool m_aplicarformuladefecto;

        private bool m_tipoimpresionresultado;
        private string m_tipohojaimpresionresultado;
        private bool m_tipoimpresionresultadomicrobiologia;
        private string m_tipohojaimpresionresultadomicrobiologia;
        
        private bool m_resultadoedad;
        private bool m_resultadofnacimiento;
        private bool m_resultadosexo;
        private bool m_resultadodni;
        private bool m_resultadohc;
        private bool m_resultadodomicilio;

        private bool m_resultadoedadmicrobiologia;
        private bool m_resultadofnacimientomicrobiologia;
        private bool m_resultadosexomicrobiologia;
        private bool m_resultadodnimicrobiologia;
        private bool m_resultadohcmicrobiologia;
        private bool m_resultadodomiciliomicrobiologia;

        private int m_firmaelectronicalaboratorio;
        private int m_firmaelectronicamicrobiologia;


        private bool m_resultadonumeroregistro;
        private bool m_resultadofechaentrega;
        private bool m_resultadosector;
        private bool m_resultadosolicitante;
        private bool m_resultadoorigen;
        private bool m_resultadoprioridad;


        private bool m_resultadonumeroregistromicrobiologia;
        private bool m_resultadofechaentregamicrobiologia;
        private bool m_resultadosectormicrobiologia;
        private bool m_resultadosolicitantemicrobiologia;
        private bool m_resultadoorigenmicrobiologia;
        private bool m_resultadoprioridadmicrobiologia;

        private int m_idOrigenUrgencia;
        private int m_idSectorUrgencia;

		private Usuario m_idusuarioregistro; 
		private DateTime m_fecharegistro;
        private bool m_ordenimpresionlaboratorio;
        private bool m_ordenimpresionmicrobiologia;

        private bool m_autenticavalidacion;
        private bool m_peticionelectronica;

        private int m_valordefectofechatomamuestra;
        private int m_valordefectofechaorden;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public Configuracion()
		{
            m_idconfiguracion = 0; 
            m_idefector = new Efector(); 
            m_nivel = 0; 
            m_rutalogo = String.Empty; 

            m_principalturno=true;
            m_principalrecepcion=true;
            m_principalimpresionht=true;
            m_principalcargaresultados=true;
            m_principalvalidacion=true;
            m_principalimpresionresultados=true;
            m_principalurgencias=true;
            m_principalresultados=true;
            //m_nombreimpresora = string.Empty;


            m_encabezadolinea1 = String.Empty; 
            m_encabezadolinea2 = String.Empty; 
            m_encabezadolinea3 = String.Empty;

            m_encabezadolinea1microbiologia = String.Empty;
            m_encabezadolinea2microbiologia = String.Empty;
            m_encabezadolinea3microbiologia = String.Empty;

            m_tiponumeracionprotocolo = 0;
            m_utilizanumeroeliminado = true;
            m_nroprotocolo = 0;
            m_recordarorigenprotocolo = false;
            m_recordarsectorprotocolo = false;
            m_tipocalculodiasretiro = 0;
            m_diasretiro = 0; 
            /////////////////////
            m_generacomprobanteprotocolo = false;
            m_generacomprobanteprotocolomicrobiologia = false;
            
            m_textoadicionalcomprobanteprotocolo = String.Empty;
            m_textoadicionalcomprobanteprotocolomicrobiologia = String.Empty;

            //////////////////////////
            m_cantidadprotocolosporpagina = 0;

            m_modificarprotocoloterminado = true;
            m_eliminarprotocoloterminado = true;

            m_turno = false; 
            m_generacomprobanteturno = false;
            m_smscancelaturno = false;
            m_tipolistaprotocolo = 0;
            m_tipohojatrabajo =0;
            m_tipocargaresultado = 0;
            m_ordencargaresultado = false;

            m_tipoimpresionresultado=true;
            m_tipoimpresionresultadomicrobiologia = true;
            

            m_aplicarformuladefecto = false;

            m_resultadoedad=true;
            m_resultadofnacimiento=true;
            m_resultadosexo=true;
            m_resultadodni=true;
            m_resultadohc=true;
            m_resultadodomicilio=true;

            m_resultadoedadmicrobiologia = true;
            m_resultadofnacimientomicrobiologia = true;
            m_resultadosexomicrobiologia = true;
            m_resultadodnimicrobiologia = true;
            m_resultadohcmicrobiologia = true;
            m_resultadodomiciliomicrobiologia = true;
            ////////////////
            //m_resultadoimprimepie = false;


            m_firmaelectronicalaboratorio=0;
            m_firmaelectronicamicrobiologia=0;
            ///////////////////////

            m_resultadonumeroregistro=true;
            m_resultadofechaentrega=true;
            m_resultadosector=true;
            m_resultadosolicitante=true;
            m_resultadoorigen=true;
            m_resultadoprioridad=true;


            m_resultadonumeroregistromicrobiologia = true;
            m_resultadofechaentregamicrobiologia = true;
            m_resultadosectormicrobiologia = true;
            m_resultadosolicitantemicrobiologia = true;
            m_resultadoorigenmicrobiologia = true;
            m_resultadoprioridadmicrobiologia = true;
            /////////////////////

            m_idOrigenUrgencia=0;
            m_idSectorUrgencia=0;

            m_idusuarioregistro = new Usuario(); 
            m_fecharegistro = DateTime.MinValue;
            m_ordenimpresionlaboratorio = false;
            m_ordenimpresionmicrobiologia = false;


            m_autenticavalidacion = false;
            m_peticionelectronica = false;

    m_valordefectofechatomamuestra=0;
        m_valordefectofechaorden=0;


    }
    #endregion // End of Default ( Empty ) Class Constuctor

    #region Required Fields Only Constructor
    /// <summary>
    /// required (not null) fields only constructor
    /// </summary>
    public Configuracion(
            Efector idefector, 
            int nivel, 
            string rutalogo, 
            bool principalturno,
            bool principalrecepcion,
            bool principalimpresionht,
            bool principalcargaresultados,
            bool principalvalidacion,
            bool principalimpresionresultados,
            bool principalurgencias,
            bool principalresultados,

            
            string encabezadolinea1, 
            string encabezadolinea2, 
            string encabezadolinea3,

            string encabezadolinea1microbiologia,
            string encabezadolinea2microbiologia,
            string encabezadolinea3microbiologia, 

            int tiponumeracionprotocolo, 
            bool utilizanumeroeliminado,
            int nroprotocolo, 
            int tipocalculodiasretiro,
            int diasretiro, 
            
            ////////////////////////
            bool generacomprobanteprotocolo,             
            string textoadicionalcomprobanteprotocolo,

            bool generacomprobanteprotocolomicrobiologia,
            string textoadicionalcomprobanteprotocolomicrobiologia,
            
        /// <summary>
        /// ////////////////
        /// </summary>

            bool recordarorigenprotocolo,
            bool recordarsectorprotocolo,
            int cantidadprotocolosporpagina,

            bool modificarprotocoloterminado ,
            bool eliminarprotocoloterminado,

            bool turno, 
            bool generacomprobanteturno, 
            bool smscancelaturno,
            int tipolistaprotocolo,
            int tipohojatrabajo,
            int tipocargaresultado,
            bool ordencargaresultado,
            bool aplicarformuladefecto,
            
            bool tipoimpresionresultado,
            string tipohojaimpresionresultado,

            bool tipoimpresionresultadomicrobiologia,
            string tipohojaimpresionresultadomicrobiologia,

            bool   resultadoedad,
            bool resultadofnacimiento,
            bool resultadosexo,
            bool resultadodni,
            bool resultadohc,
            bool resultadodomicilio,


             bool resultadoedadmicrobiologia,
            bool resultadofnacimientomicrobiologia,
            bool resultadosexomicrobiologia,
            bool resultadodnimicrobiologia,
            bool resultadohcmicrobiologia,
            bool resultadodomiciliomicrobiologia,
            
            
            int firmaelectronicalaboratorio,
            int firmaelectronicamicrobiologia,

            bool resultadoNumeroRegistro,
            bool resultadoFechaEntrega,
            bool resultadoSector,
            bool resultadoSolicitante,
            bool resultadoOrigen,
            bool resultadoPrioridad,

             bool resultadoNumeroRegistromicrobiologia,
            bool resultadoFechaEntregamicrobiologia,
            bool resultadoSectormicrobiologia,
            bool resultadoSolicitantemicrobiologia,
            bool resultadoOrigenmicrobiologia,
            bool resultadoPrioridadmicrobiologia,

            int idOrigenUrgencia,
            int idSectorUrgencia,

            Usuario idusuarioregistro, 
            DateTime fecharegistro,
            bool ordenimpresionlaboratorio,
            bool ordenimpresionmicrobiologia,
            bool autenticavalidacion,
           bool peticionelectronica,
int valordefectofechatomamuestra,
        int valordefectofechaorden

       
            )
            : this()
		{
            m_idefector = idefector;
            m_nivel = nivel;
            m_rutalogo = rutalogo;
            m_principalrecepcion=principalrecepcion;
            m_principalimpresionht=principalimpresionht;
            m_principalcargaresultados=principalcargaresultados;
            m_principalvalidacion=principalvalidacion;
            m_principalimpresionresultados=principalimpresionresultados;
            m_principalurgencias = principalurgencias;
            m_principalresultados = principalresultados;

            //m_nombreimpresora = nombreimpresora;
            m_encabezadolinea1 = encabezadolinea1;
            m_encabezadolinea2 = encabezadolinea2;
            m_encabezadolinea3 = encabezadolinea3;

            m_encabezadolinea1microbiologia = encabezadolinea1microbiologia;
            m_encabezadolinea2microbiologia = encabezadolinea2microbiologia;
            m_encabezadolinea3microbiologia = encabezadolinea3microbiologia;

            m_tiponumeracionprotocolo = tiponumeracionprotocolo;
            m_utilizanumeroeliminado = utilizanumeroeliminado;
            m_nroprotocolo = nroprotocolo;
            m_tipocalculodiasretiro = tipocalculodiasretiro;
            m_diasretiro = diasretiro;

            m_generacomprobanteprotocolo = generacomprobanteprotocolo;
            m_textoadicionalcomprobanteprotocolo = textoadicionalcomprobanteprotocolo;

            m_generacomprobanteprotocolomicrobiologia = generacomprobanteprotocolomicrobiologia;
            m_textoadicionalcomprobanteprotocolomicrobiologia = textoadicionalcomprobanteprotocolomicrobiologia;

            m_cantidadprotocolosporpagina = cantidadprotocolosporpagina;
            m_turno = turno;
            m_generacomprobanteturno = generacomprobanteturno;
            m_smscancelaturno = smscancelaturno;
            m_recordarorigenprotocolo = recordarorigenprotocolo;
            m_recordarsectorprotocolo = recordarsectorprotocolo;
            m_modificarprotocoloterminado = modificarprotocoloterminado;
            m_eliminarprotocoloterminado = eliminarprotocoloterminado;

            m_tipolistaprotocolo = tipolistaprotocolo;
            m_tipohojatrabajo = tipohojatrabajo;
            m_tipocargaresultado = tipocargaresultado;
            m_ordencargaresultado = ordencargaresultado;

            m_tipoimpresionresultado = tipoimpresionresultado;
            m_tipohojaimpresionresultado = tipohojaimpresionresultado;


            m_tipoimpresionresultadomicrobiologia= tipoimpresionresultadomicrobiologia;
            m_tipohojaimpresionresultadomicrobiologia = tipohojaimpresionresultadomicrobiologia;

            m_aplicarformuladefecto = aplicarformuladefecto;

            m_resultadoedad=resultadoedad;
            m_resultadofnacimiento =resultadofnacimiento;
            m_resultadosexo=        resultadosexo;
            m_resultadodni=       resultadodni;
            m_resultadohc=resultadohc;
            m_resultadodomicilio=resultadodomicilio;


            m_resultadoedadmicrobiologia = resultadoedadmicrobiologia;
            m_resultadofnacimientomicrobiologia = resultadofnacimientomicrobiologia;
            m_resultadosexomicrobiologia = resultadosexomicrobiologia;
            m_resultadodnimicrobiologia = resultadodnimicrobiologia;
            m_resultadohcmicrobiologia = resultadohcmicrobiologia;
            m_resultadodomiciliomicrobiologia = resultadodomiciliomicrobiologia;

            m_firmaelectronicalaboratorio = firmaelectronicalaboratorio;
            m_firmaelectronicamicrobiologia = firmaelectronicamicrobiologia;

            m_resultadonumeroregistro = resultadoNumeroRegistro;
            m_resultadofechaentrega=         resultadoFechaEntrega;
            m_resultadosector =resultadoSector;
            m_resultadosolicitante=        resultadoSolicitante;
            m_resultadoorigen= resultadoOrigen;
            m_resultadoprioridad=resultadoPrioridad;

            m_resultadonumeroregistromicrobiologia = resultadoNumeroRegistromicrobiologia;
            m_resultadofechaentregamicrobiologia = resultadoFechaEntregamicrobiologia;
            m_resultadosectormicrobiologia = resultadoSectormicrobiologia;
            m_resultadosolicitantemicrobiologia = resultadoSolicitantemicrobiologia;
            m_resultadoorigenmicrobiologia = resultadoOrigenmicrobiologia;
            m_resultadoprioridadmicrobiologia = resultadoPrioridadmicrobiologia;


            m_idOrigenUrgencia = idOrigenUrgencia;
            m_idSectorUrgencia= idSectorUrgencia;


            m_idusuarioregistro = idusuarioregistro;
            m_fecharegistro = fecharegistro;
            m_ordenimpresionlaboratorio = ordenimpresionlaboratorio;
            m_ordenimpresionmicrobiologia = ordenimpresionmicrobiologia;


            m_autenticavalidacion = autenticavalidacion;
            m_peticionelectronica = peticionelectronica;

            m_valordefectofechaorden = valordefectofechaorden;
            m_valordefectofechatomamuestra = valordefectofechatomamuestra;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdConfiguracion
		{
			get { return m_idconfiguracion; }
			set
			{
				m_isChanged |= ( m_idconfiguracion != value ); 
				m_idconfiguracion = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Efector IdEfector
		{
			get { return m_idefector; }
			set
			{
				m_isChanged |= ( m_idefector != value ); 
				m_idefector = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int Nivel
		{
			get { return m_nivel; }
			set
			{
				m_isChanged |= ( m_nivel != value ); 
				m_nivel = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string RutaLogo
		{
			get { return m_rutalogo; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RutaLogo", value, "null");
				
				if(  value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for RutaLogo", value, value.ToString());
				
				m_isChanged |= (m_rutalogo != value); m_rutalogo = value;
			}
		}



      
        /// <summary>
        /// Atributos de configuración de la pantalla principal: Accesos Directos
        /// </summary>
        public bool PrincipalTurno
        {
            get { return m_principalturno; }
            set
            {
                m_isChanged |= (m_principalturno != value);
                m_principalturno = value;
            }

        }


        public bool PrincipalRecepcion
        {
            get { return m_principalrecepcion; }
            set
            {
                m_isChanged |= (m_principalrecepcion != value);
                m_principalrecepcion = value;
            }

        }
        public bool PrincipalImpresionHT
        {
            get { return m_principalimpresionht; }
            set
            {
                m_isChanged |= (m_principalimpresionht != value);
                m_principalimpresionht = value;
            }

        }

        public bool PrincipalCargaResultados
        {
            get { return m_principalcargaresultados; }
            set
            {
                m_isChanged |= (m_principalcargaresultados != value);
                m_principalcargaresultados = value;
           }
        }

        public bool PrincipalValidacion
        {
            get { return m_principalvalidacion; }
            set
            {
                m_isChanged |= (m_principalvalidacion != value);
                m_principalvalidacion = value;
            }

        }

        public bool PrincipalImpresionResultados
        {
            get { return m_principalimpresionresultados; }
            set
            {
                m_isChanged |= (m_principalimpresionresultados != value);
                m_principalimpresionresultados = value;
            }
        }

        public bool PrincipalUrgencias
        {
            get { return m_principalurgencias; }
            set
            {
                m_isChanged |= (m_principalurgencias != value);
                m_principalurgencias = value;
            }
        }

        public bool PrincipalResultados
        {
            get { return m_principalresultados; }
            set
            {
                m_isChanged |= (m_principalresultados != value);
                m_principalresultados = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public string EncabezadoLinea1
		{
			get { return m_encabezadolinea1; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for EncabezadoLinea1", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for EncabezadoLinea1", value, value.ToString());
				
				m_isChanged |= (m_encabezadolinea1 != value); m_encabezadolinea1 = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string EncabezadoLinea2
		{
			get { return m_encabezadolinea2; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for EncabezadoLinea2", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for EncabezadoLinea2", value, value.ToString());
				
				m_isChanged |= (m_encabezadolinea2 != value); m_encabezadolinea2 = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string EncabezadoLinea3
		{
			get { return m_encabezadolinea3; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for EncabezadoLinea3", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for EncabezadoLinea3", value, value.ToString());
				
				m_isChanged |= (m_encabezadolinea3 != value); m_encabezadolinea3 = value;
			}
		}



        public string EncabezadoLinea1Microbiologia
        {
            get { return m_encabezadolinea1microbiologia; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_encabezadolinea1microbiologia", value, "null");

                if (value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for m_encabezadolinea1microbiologia", value, value.ToString());

                m_isChanged |= (m_encabezadolinea1microbiologia != value); m_encabezadolinea1microbiologia = value;
            }
        }


        public string EncabezadoLinea2Microbiologia
        {
            get { return m_encabezadolinea2microbiologia; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_encabezadolinea2microbiologia", value, "null");

                if (value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for m_encabezadolinea2microbiologia", value, value.ToString());

                m_isChanged |= (m_encabezadolinea2microbiologia != value); m_encabezadolinea2microbiologia = value;
            }
        }

        public string EncabezadoLinea3Microbiologia
        {
            get { return m_encabezadolinea3microbiologia; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_encabezadolinea3microbiologia", value, "null");

                if (value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for m_encabezadolinea3microbiologia", value, value.ToString());

                m_isChanged |= (m_encabezadolinea3microbiologia != value); m_encabezadolinea3microbiologia = value;
            }
        }
			
			
		/// <summary>
		/// 
		/// </summary>
		public int TipoNumeracionProtocolo
		{
			get { return m_tiponumeracionprotocolo; }
			set
			{
				m_isChanged |= ( m_tiponumeracionprotocolo != value ); 
				m_tiponumeracionprotocolo = value;
			}

		}


        public bool UtilizaNumeroEliminado
        {
            get { return m_utilizanumeroeliminado; }
            set
            {
                m_isChanged |= (m_utilizanumeroeliminado != value);
                m_utilizanumeroeliminado = value;
            }

        }
		/// <summary>
		/// 
		/// </summary>
		public int NroProtocolo
		{
			get { return m_nroprotocolo; }
			set
			{
				m_isChanged |= ( m_nroprotocolo != value ); 
				m_nroprotocolo = value;
			}

		}


        /// <summary>
        /// 
        /// </summary>
        public int TipoCalculoDiasRetiro
        {
            get { return m_tipocalculodiasretiro; }
            set
            {
                m_isChanged |= (m_tipocalculodiasretiro != value);
                m_tipocalculodiasretiro = value;
            }

        }
			
		/// <summary>
		/// 
		/// </summary>
		public int DiasRetiro
		{
			get { return m_diasretiro; }
			set
			{
				m_isChanged |= ( m_diasretiro != value ); 
				m_diasretiro = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public bool GeneraComprobanteProtocolo
		{
			get { return m_generacomprobanteprotocolo; }
			set
			{
				m_isChanged |= ( m_generacomprobanteprotocolo != value ); 
				m_generacomprobanteprotocolo = value;
			}

		}


       
        public bool GeneraComprobanteProtocoloMicrobiologia
        {
            get { return m_generacomprobanteprotocolomicrobiologia; }
            set
            {
                m_isChanged |= (m_generacomprobanteprotocolomicrobiologia != value);
                m_generacomprobanteprotocolomicrobiologia = value;
            }

        }


        public string TextoAdicionalComprobanteProtocolo
        {
            get { return m_textoadicionalcomprobanteprotocolo; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_textoadicionalcomprobanteprotocolo", value, "null");

                if (value.Length > 500)
                    throw new ArgumentOutOfRangeException("Invalid value for m_textoadicionalcomprobanteprotocolo", value, value.ToString());

                m_isChanged |= (m_textoadicionalcomprobanteprotocolo != value); m_textoadicionalcomprobanteprotocolo = value;
            }
        }


        public string TextoAdicionalComprobanteProtocoloMicrobiologia
        {
            get { return m_textoadicionalcomprobanteprotocolomicrobiologia; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_textoadicionalcomprobanteprotocolomicrobiologia", value, "null");

                if (value.Length > 500)
                    throw new ArgumentOutOfRangeException("Invalid value for m_textoadicionalcomprobanteprotocolomicrobiologia", value, value.ToString());

                m_isChanged |= (m_textoadicionalcomprobanteprotocolomicrobiologia != value); m_textoadicionalcomprobanteprotocolomicrobiologia = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>

        public bool RecordarOrigenProtocolo
        {
            get { return m_recordarorigenprotocolo; }
            set
            {
                m_isChanged |= (m_recordarorigenprotocolo != value);
                m_recordarorigenprotocolo = value;
            }

        }
        public bool RecordarSectorProtocolo
        {
            get { return m_recordarsectorprotocolo; }
            set
            {
                m_isChanged |= (m_recordarsectorprotocolo != value);
                m_recordarsectorprotocolo = value;
            }

        }

        public bool ModificarProtocoloTerminado
        {
            get { return m_modificarprotocoloterminado; }
            set
            {
                m_isChanged |= (m_modificarprotocoloterminado != value);
                m_modificarprotocoloterminado = value;
            }

        }

        public bool EliminarProtocoloTerminado
        {
            get { return m_eliminarprotocoloterminado; }
            set
            {
                m_isChanged |= (m_eliminarprotocoloterminado != value);
                m_eliminarprotocoloterminado = value;
            }

        }

        public int CantidadProtocolosPorPagina
        {
            get { return m_cantidadprotocolosporpagina; }
            set
            {
                m_isChanged |= (m_cantidadprotocolosporpagina != value);
                m_cantidadprotocolosporpagina = value;
            }

        }
		/// <summary>
		/// 
		/// </summary>
		public bool Turno
		{
			get { return m_turno; }
			set
			{
				m_isChanged |= ( m_turno != value ); 
				m_turno = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public bool GeneraComprobanteTurno
		{
			get { return m_generacomprobanteturno; }
			set
			{
				m_isChanged |= ( m_generacomprobanteturno != value ); 
				m_generacomprobanteturno = value;
			}

		}
        public bool SmsCancelaTurno
        {
            get { return m_smscancelaturno; }
            set
            {
                m_isChanged |= (m_smscancelaturno != value);
                m_smscancelaturno = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public int TipoListaProtocolo
        {
            get { return m_tipolistaprotocolo; }
            set
            {
                m_isChanged |= (m_tipolistaprotocolo != value);
                m_tipolistaprotocolo = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public int TipoHojaTrabajo
        {
            get { return m_tipohojatrabajo; }
            set
            {
                m_isChanged |= (m_tipohojatrabajo != value);
                m_tipohojatrabajo = value;
            }

        }

        /// <summary>
        /// 
        /// </summary>
        public int TipoCargaResultado
        {
            get { return m_tipocargaresultado; }
            set
            {
                m_isChanged |= (m_tipocargaresultado != value);
                m_tipocargaresultado = value;
            }

        }

        public bool OrdenCargaResultado
        {
            get { return m_ordencargaresultado; }
            set
            {
                m_isChanged |= (m_ordencargaresultado != value);
                m_ordencargaresultado = value;
            }

        }

        public bool TipoImpresionResultado
        {
            get { return m_tipoimpresionresultado; }
            set
            {
                m_isChanged |= (m_tipoimpresionresultado != value);
                m_tipoimpresionresultado = value;
            }

        }



        public bool TipoImpresionResultadoMicrobiologia
        {
            get { return m_tipoimpresionresultadomicrobiologia; }
            set
            {
                m_isChanged |= (m_tipoimpresionresultadomicrobiologia != value);
                m_tipoimpresionresultadomicrobiologia = value;
            }

        }


        public string TipoHojaImpresionResultado
        {
            get { return m_tipohojaimpresionresultado; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_nombreimpresora", value, "null");

                if (value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for m_nombreimpresora", value, value.ToString());

                m_isChanged |= (m_tipohojaimpresionresultado != value); m_tipohojaimpresionresultado = value;
            }
        }


        public string TipoHojaImpresionResultadoMicrobiologia
        {
            get { return m_tipohojaimpresionresultadomicrobiologia; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for m_tipohojaimpresionresultadomicrobiologia", value, "null");

                if (value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for m_tipohojaimpresionresultadomicrobiologia", value, value.ToString());

                m_isChanged |= (m_tipohojaimpresionresultadomicrobiologia != value); m_tipohojaimpresionresultadomicrobiologia = value;
            }
        }


        public bool AplicarFormulaDefecto
        {
            get { return m_aplicarformuladefecto; }
            set
            {
                m_isChanged |= (m_aplicarformuladefecto != value);
                m_aplicarformuladefecto = value;
            }

        }

        public bool ResultadoEdad
        {
            get { return m_resultadoedad; }
            set
            {
                m_isChanged |= (m_resultadoedad != value);
                m_resultadoedad = value;
            }

        }

        public bool ResultadoFNacimiento
        {
            get { return m_resultadofnacimiento; }
            set
            {
                m_isChanged |= (m_resultadofnacimiento != value);
                m_resultadofnacimiento = value;
            }

        }

        public bool ResultadoSexo
        {
            get { return m_resultadosexo; }
            set
            {
                m_isChanged |= (m_resultadosexo != value);
                m_resultadosexo = value;
            }

        }

        public bool ResultadoDNI
        {
            get { return m_resultadodni; }
            set
            {
                m_isChanged |= (m_resultadodni != value);
                m_resultadodni = value;
            }

        }


        public bool ResultadoHC
        {
            get { return m_resultadohc; }
            set
            {
                m_isChanged |= (m_resultadohc != value);
                m_resultadohc = value;
            }

        }

        public bool ResultadoDomicilio
        {
            get { return m_resultadodomicilio; }
            set
            {
                m_isChanged |= (m_resultadodomicilio != value);
                m_resultadodomicilio = value;
            }

        }

        /// <summary>
        /// ///////////////////////////Microbiologia

        public bool ResultadoEdadMicrobiologia
        {
            get { return m_resultadoedadmicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadoedadmicrobiologia != value);
                m_resultadoedadmicrobiologia = value;
            }

        }

        public bool ResultadoFNacimientoMicrobiologia
        {
            get { return m_resultadofnacimientomicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadofnacimientomicrobiologia != value);
                m_resultadofnacimientomicrobiologia = value;
            }

        }

        public bool ResultadoSexoMicrobiologia
        {
            get { return m_resultadosexomicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadosexomicrobiologia != value);
                m_resultadosexomicrobiologia = value;
            }

        }

        public bool ResultadoDNIMicrobiologia
        {
            get { return m_resultadodnimicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadodnimicrobiologia != value);
                m_resultadodnimicrobiologia = value;
            }

        }


        public bool ResultadoHCMicrobiologia
        {
            get { return m_resultadohcmicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadohcmicrobiologia != value);
                m_resultadohcmicrobiologia = value;
            }

        }

        public bool ResultadoDomicilioMicrobiologia
        {
            get { return m_resultadodomiciliomicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadodomiciliomicrobiologia != value);
                m_resultadodomiciliomicrobiologia = value;
            }

        }
        /// 
        /// </summary>

        public int FirmaElectronicaLaboratorio
        {
            get { return m_firmaelectronicalaboratorio; }
            set
            {
                m_isChanged |= (m_firmaelectronicalaboratorio != value);
                m_firmaelectronicalaboratorio = value;
            }

        }


        public int FirmaElectronicaMicrobiologia
        {
            get { return m_firmaelectronicamicrobiologia; }
            set
            {
                m_isChanged |= (m_firmaelectronicamicrobiologia != value);
                m_firmaelectronicamicrobiologia = value;
            }

        }


        public bool ResultadoNumeroRegistro	
        {
            get { return m_resultadonumeroregistro; }
            set
            {
                m_isChanged |= (m_resultadonumeroregistro != value);
                m_resultadonumeroregistro = value;
            }

        }

        public bool ResultadoFechaEntrega	
        {
            get { return m_resultadofechaentrega; }
            set
            {
                m_isChanged |= (m_resultadofechaentrega != value);
                m_resultadofechaentrega = value;
            }

        }

        public bool ResultadoSector	
        {
            get { return m_resultadosector; }
            set
            {
                m_isChanged |= (m_resultadosector != value);
                m_resultadosector = value;
            }

        }


        public bool ResultadoSolicitante	
        {
            get { return m_resultadosolicitante; }
            set
            {
                m_isChanged |= (m_resultadosolicitante != value);
                m_resultadosolicitante = value;
            }

        }

        public bool ResultadoOrigen	
        {
            get { return m_resultadoorigen; }
            set
            {
                m_isChanged |= (m_resultadoorigen != value);
                m_resultadoorigen = value;
            }

        }

        public bool ResultadoPrioridad	
        {
            get { return m_resultadoprioridad; }
            set
            {
                m_isChanged |= (m_resultadoprioridad != value);
                m_resultadoprioridad = value;
            }

        }


        /// <summary>
        /// //////////////////////////MICROBIOLOGIA
        public bool ResultadoNumeroRegistroMicrobiologia
        {

            get { return m_resultadonumeroregistromicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadonumeroregistromicrobiologia != value);
                m_resultadonumeroregistromicrobiologia = value;
            }

        }

        public bool ResultadoFechaEntregaMicrobiologia
        {
            get { return m_resultadofechaentregamicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadofechaentregamicrobiologia != value);
                m_resultadofechaentregamicrobiologia = value;
            }

        }

        public bool ResultadoSectorMicrobiologia
        {
            get { return m_resultadosectormicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadosectormicrobiologia != value);
                m_resultadosectormicrobiologia = value;
            }

        }


        public bool ResultadoSolicitanteMicrobiologia
        {
            get { return m_resultadosolicitantemicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadosolicitantemicrobiologia != value);
                m_resultadosolicitantemicrobiologia = value;
            }

        }

        public bool ResultadoOrigenMicrobiologia
        {
            get { return m_resultadoorigenmicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadoorigenmicrobiologia != value);
                m_resultadoorigenmicrobiologia = value;
            }

        }

        public bool ResultadoPrioridadMicrobiologia
        {
            get { return m_resultadoprioridadmicrobiologia; }
            set
            {
                m_isChanged |= (m_resultadoprioridadmicrobiologia != value);
                m_resultadoprioridadmicrobiologia = value;
            }

        }


        /// </summary>

        public int IdOrigenUrgencia
        {
            get { return m_idOrigenUrgencia; }
            set
            {
                m_isChanged |= (m_idOrigenUrgencia != value);
                m_idOrigenUrgencia = value;
            }

        }


        public int IdSectorUrgencia
        {
            get { return m_idSectorUrgencia; }
            set
            {
                m_isChanged |= (m_idSectorUrgencia != value);
                m_idSectorUrgencia = value;
            }

        }
		///
        /// <summary>
		/// 
		/// </summary>
		public Usuario IdUsuarioRegistro
		{
			get { return m_idusuarioregistro; }
			set
			{
				m_isChanged |= ( m_idusuarioregistro != value ); 
				m_idusuarioregistro = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime FechaRegistro
		{
			get { return m_fecharegistro; }
			set
			{
				m_isChanged |= ( m_fecharegistro != value ); 
				m_fecharegistro = value;
			}

		}

        public bool OrdenImpresionLaboratorio
        {
            get { return m_ordenimpresionlaboratorio; }
            set
            {
                m_isChanged |= (m_ordenimpresionlaboratorio != value);
                m_ordenimpresionlaboratorio = value;
            }

        }

        public bool OrdenImpresionMicrobiologia
        {
            get { return m_ordenimpresionmicrobiologia; }
            set
            {
                m_isChanged |= (m_ordenimpresionmicrobiologia != value);
                m_ordenimpresionmicrobiologia = value;
            }

        }

      


        public bool AutenticaValidacion
        {
            get { return m_autenticavalidacion; }
            set
            {
                m_isChanged |= (m_autenticavalidacion != value);
                m_autenticavalidacion = value;
            }

        }


        public bool PeticionElectronica
        {
            get { return m_peticionelectronica; }
            set
            {
                m_isChanged |= (m_peticionelectronica != value);
                m_peticionelectronica = value;
            }

        }


        public int ValorDefectoFechaTomaMuestra
        {
            get { return m_valordefectofechatomamuestra; }
            set
            {
                m_isChanged |= (m_valordefectofechatomamuestra != value);
                m_valordefectofechatomamuestra = value;
            }

        }

        public int ValorDefectoFechaOrden
        {
            get { return m_valordefectofechaorden; }
            set
            {
                m_isChanged |= (m_valordefectofechaorden != value);
                m_valordefectofechaorden = value;
            }

        }
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
