/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class IndicenciaRecepcion: Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idindicenciarecepcion; 
		private int m_idefector; 
		private int m_idusuario; 
		private DateTime m_fecha;
        private DateTime m_fecharegistro;
		private bool m_baja;
        private int m_idefectororigen; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public IndicenciaRecepcion()
		{
			m_idindicenciarecepcion = 0; 
			m_idefector = 0; 
			m_idusuario = 0; 
			m_fecha = DateTime.MinValue;
            m_fecharegistro = DateTime.MinValue; 
			m_baja = false;
            m_idefectororigen = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public IndicenciaRecepcion(
			int idefector, 
			int idusuario, 
			DateTime fecha, 
            DateTime fecharegistro,
			bool baja,
            int idefectororigen)
			: this()
		{
			m_idefector = idefector;
			m_idusuario = idusuario;
			m_fecha = fecha;
            m_fecharegistro = fecharegistro;
			m_baja = baja;
            m_idefectororigen = idefectororigen;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdIndicenciaRecepcion
		{
			get { return m_idindicenciarecepcion; }
			set
			{
				m_isChanged |= ( m_idindicenciarecepcion != value ); 
				m_idindicenciarecepcion = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int IdEfector
		{
			get { return m_idefector; }
			set
			{
				m_isChanged |= ( m_idefector != value ); 
				m_idefector = value;
			}

		}
        public int IdEfectorOrigen
        {
            get { return m_idefectororigen; }
            set
            {
                m_isChanged |= (m_idefectororigen != value);
                m_idefectororigen = value;
            }

        }
			
		/// <summary>
		/// 
		/// </summary>
		public int IdUsuario
		{
			get { return m_idusuario; }
			set
			{
				m_isChanged |= ( m_idusuario != value ); 
				m_idusuario = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime Fecha
		{
			get { return m_fecha; }
			set
			{
				m_isChanged |= ( m_fecha != value ); 
				m_fecha = value;
			}

		}
        /// <summary>
        /// 
        /// </summary>
        public DateTime FechaRegistro
        {
            get { return m_fecharegistro; }
            set
            {
                m_isChanged |= (m_fecharegistro != value);
                m_fecharegistro = value;
            }

        }
			
		/// <summary>
		/// 
		/// </summary>
		public bool Baja
		{
			get { return m_baja; }
			set
			{
				m_isChanged |= ( m_baja != value ); 
				m_baja = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
