/*
insert license info here
*/
using System;
using System.Collections;
using System.Data;
using System.Data.SqlClient;
using NHibernate;
using NHibernate.Expression;
using MathParser;
using System.IO;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Protocolo : Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idprotocolo; 
		private Efector m_idefector; 
		private int m_numero;
        private int m_numerotiposervicio;
		private int m_numerodiario;
        private string m_prefijosector;
        private int m_numerosector;
        private SectorServicio m_idsector;
		private TipoServicio m_idtiposervicio; 
		private DateTime m_fecha; 
		private DateTime m_fechaorden; 
		private DateTime m_fecharetiro; 
		private Paciente m_idpaciente; 
		private Efector m_idefectorsolicitante; 
		private int m_idespecialistasolicitante; 
		private ObraSocial m_idobrasocial; 
		private Origen m_idorigen; 
		private Prioridad m_idprioridad; 
		private string m_observacion;
        private string m_sala;
        private string m_cama;
        private bool m_alerta;
        private int m_edad;
        private int m_unidadedad;
        private string m_sexo;
        private string m_embarazada;
        //private string m_horanacimiento;
        //private int m_pesonacimiento;
        //private int m_semanagestacion;
        private string m_numeroorigen;
        //private string m_reciennacido;
        private bool m_baja;
        private bool m_impreso;
        private int m_estado;
		private Usuario m_idusuarioregistro; 
		private DateTime m_fecharegistro;
        private string m_observacionResultado;
        private int m_idmuestra;
        private DateTime m_fechatomamuestra;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public Protocolo()
		{
			m_idprotocolo = 0; 
			m_idefector = new Efector(); 
			m_numero = 0; 
			m_numerodiario = 0;
            m_prefijosector = String.Empty;
            m_numerosector = 0;
            m_numerotiposervicio = 0;
            m_idsector = new SectorServicio(); 
			m_idtiposervicio = new TipoServicio(); 
			m_fecha = DateTime.MinValue; 
			m_fechaorden = DateTime.MinValue; 
			m_fecharetiro = DateTime.MinValue; 
			m_idpaciente = new Paciente(); 
			m_idefectorsolicitante = new Efector(); 
			m_idespecialistasolicitante = 0; 
			m_idobrasocial = new ObraSocial(); 
			m_idorigen = new Origen(); 
			m_idprioridad = new Prioridad(); 
			m_observacion = String.Empty;
            m_sala = String.Empty;
            m_cama = String.Empty;
            m_estado = 0;
            m_edad = 0;
            m_unidadedad = 0;
            m_sexo = String.Empty;
            m_embarazada = String.Empty;
            //m_horanacimiento = String.Empty;
            //m_pesonacimiento = 0;
            //m_semanagestacion = 0;
            m_numeroorigen = String.Empty;
            //m_reciennacido= String.Empty                ;
            m_alerta = false;
		
			m_idusuarioregistro = new Usuario(); 
			m_fecharegistro = DateTime.MinValue;
            m_fechatomamuestra = DateTime.MinValue;
            m_idmuestra = 0; 
            
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public Protocolo(
			Efector idefector, 
			int numero, 
            int numerotiposervicio,
			int numerodiario, 
            string prefijosector,
            int numerosector,
            SectorServicio idsector, 
			TipoServicio idtiposervicio, 
			DateTime fecha, 
			DateTime fechaorden, 
			DateTime fecharetiro, 
			Paciente idpaciente, 
			Efector idefectorsolicitante, 
			int idespecialistasolicitante, 
			ObraSocial idobrasocial, 
			Origen idorigen, 
			Prioridad idprioridad, 
            int  estado,
			int edad,
            int unidadedad,
            string sexo,
            string embarazada,
            //string reciennacido,
            bool alerta,
            string observacionResultado,
			Usuario idusuarioregistro, 
			DateTime fecharegistro,
            DateTime fechatomamuestra,
            	int idmuestra)
			: this()
		{
			m_idefector = idefector;
			m_numero = numero;
            m_numerotiposervicio = numerotiposervicio;
			m_numerodiario = numerodiario;
            m_prefijosector = prefijosector;
            m_numerosector = numerosector;
            m_idsector = idsector;
			m_idtiposervicio = idtiposervicio;
			m_fecha = fecha;
			m_fechaorden = fechaorden;
			m_fecharetiro = fecharetiro;
			m_idpaciente = idpaciente;
			m_idefectorsolicitante = idefectorsolicitante;
			m_idespecialistasolicitante = idespecialistasolicitante;
			m_idobrasocial = idobrasocial;
			m_idorigen = idorigen;
			m_idprioridad = idprioridad;
			m_observacion = String.Empty;
            m_sala = String.Empty;
            m_cama = String.Empty;
            m_estado = estado;
            m_edad = edad;
            m_unidadedad = unidadedad;
            m_sexo = sexo;
            m_embarazada= embarazada;
            //m_reciennacido = reciennacido;
            m_observacionResultado = observacionResultado;
            m_alerta = alerta;
			m_idusuarioregistro = idusuarioregistro;
			m_fecharegistro = fecharegistro;
            m_idmuestra = idmuestra;
            m_fechatomamuestra = fechatomamuestra;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdProtocolo
		{
			get { return m_idprotocolo; }
			set
			{
				m_isChanged |= ( m_idprotocolo != value ); 
				m_idprotocolo = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Efector IdEfector
		{
			get { return m_idefector; }
			set
			{
				m_isChanged |= ( m_idefector != value ); 
				m_idefector = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int Numero
		{
			get { return m_numero; }
			set
			{
				m_isChanged |= ( m_numero != value ); 
				m_numero = value;
			}

		}
        public int NumeroTipoServicio
        {
            get { return m_numerotiposervicio; }
            set
            {
                m_isChanged |= (m_numerotiposervicio != value);
                m_numerotiposervicio = value;
            }

        }
		/// <summary>
		/// 
		/// </summary>
		public int NumeroDiario
		{
			get { return m_numerodiario; }
			set
			{
				m_isChanged |= ( m_numerodiario != value ); 
				m_numerodiario = value;
			}

		}


        public string PrefijoSector
        {
            get { return m_prefijosector; }

            set
            {
                if (value != null && value.Length > 10)
                    throw new ArgumentOutOfRangeException("Invalid value for m_prefijogrupo", value, value.ToString());

                m_isChanged |= (m_prefijosector != value); m_prefijosector = value;
            }
        }


        public int NumeroSector
        {
            get { return m_numerosector; }
            set
            {
                m_isChanged |= (m_numerosector != value);
                m_numerosector = value;
            }

        }
		/// <summary>
		/// 
		/// </summary>
		public TipoServicio IdTipoServicio
		{
			get { return m_idtiposervicio; }
			set
			{
				m_isChanged |= ( m_idtiposervicio != value ); 
				m_idtiposervicio = value;
			}

		}

        /// <summary>
        /// 
        /// </summary>
        public SectorServicio IdSector
        {
            get { return m_idsector; }
            set
            {
                m_isChanged |= (m_idsector != value);
                m_idsector = value;
            }

        }
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime Fecha
		{
			get { return m_fecha; }
			set
			{
				m_isChanged |= ( m_fecha != value ); 
				m_fecha = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime FechaOrden
		{
			get { return m_fechaorden; }
			set
			{
				m_isChanged |= ( m_fechaorden != value ); 
				m_fechaorden = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime FechaRetiro
		{
			get { return m_fecharetiro; }
			set
			{
				m_isChanged |= ( m_fecharetiro != value ); 
				m_fecharetiro = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Paciente IdPaciente
		{
			get { return m_idpaciente; }
			set
			{
				m_isChanged |= ( m_idpaciente != value ); 
				m_idpaciente = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Efector IdEfectorSolicitante
		{
			get { return m_idefectorsolicitante; }
			set
			{
				m_isChanged |= ( m_idefectorsolicitante != value ); 
				m_idefectorsolicitante = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int IdEspecialistaSolicitante
		{
			get { return m_idespecialistasolicitante; }
			set
			{
				m_isChanged |= ( m_idespecialistasolicitante != value ); 
				m_idespecialistasolicitante = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public ObraSocial IdObraSocial
		{
			get { return m_idobrasocial; }
			set
			{
				m_isChanged |= ( m_idobrasocial != value ); 
				m_idobrasocial = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Origen IdOrigen
		{
			get { return m_idorigen; }
			set
			{
				m_isChanged |= ( m_idorigen != value ); 
				m_idorigen = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Prioridad IdPrioridad
		{
			get { return m_idprioridad; }
			set
			{
				m_isChanged |= ( m_idprioridad != value ); 
				m_idprioridad = value;
			}

		}

        public int Edad
        {
            get { return m_edad; }
            set
            {
                m_isChanged |= (m_edad != value);
                m_edad = value;
            }

        }
        public int UnidadEdad
        {
            get { return m_unidadedad; }
            set
            {
                m_isChanged |= (m_unidadedad != value);
                m_unidadedad = value;
            }

        }

        public string Sexo
        {
            get { return m_sexo; }

            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for Sexo", value, value.ToString());

                m_isChanged |= (m_sexo != value); m_sexo = value;
            }
        }

        public string Embarazada
        {
            get { return m_embarazada; }

            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for m_embarazada", value, value.ToString());

                m_isChanged |= (m_embarazada != value); m_embarazada = value;
            }
        }

        //public string HoraNacimiento
        //{
        //    get { return m_horanacimiento; }

        //    set
        //    {
        //        if (value != null && value.Length > 5)
        //            throw new ArgumentOutOfRangeException("Invalid value for m_horanacimiento", value, value.ToString());

        //        m_isChanged |= (m_horanacimiento != value); m_horanacimiento = value;
        //    }
        //}

        //public int PesoNacimiento
        //{
        //    get { return m_pesonacimiento; }
        //    set
        //    {
        //        m_isChanged |= (m_pesonacimiento != value);
        //        m_pesonacimiento = value;
        //    }

        //}

        //public int SemanaGestacion
        //{
        //    get { return m_semanagestacion; }
        //    set
        //    {
        //        m_isChanged |= (m_semanagestacion != value);
        //        m_semanagestacion = value;
        //    }

        //}

        public string NumeroOrigen
        {
            get { return m_numeroorigen; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for m_numeroextraccion", value, value.ToString());

                m_isChanged |= (m_numeroorigen != value); m_numeroorigen = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public string Observacion
		{
			get { return m_observacion; }

			set	
			{	
				if(  value != null &&  value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Observaciones", value, value.ToString());
				
				m_isChanged |= (m_observacion != value); m_observacion = value;
			}
		}

        public string ObservacionResultado
        {
            get { return m_observacionResultado; }

            set
            {
                if (value != null && value.Length > 4000)
                    throw new ArgumentOutOfRangeException("Invalid value for m_observacionResultado", value, value.ToString());

                m_isChanged |= (m_observacionResultado != value); m_observacionResultado = value;
            }
        }

        public string Sala
        {
            get { return m_sala; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for m_sala", value, value.ToString());

                m_isChanged |= (m_sala != value); m_sala = value;
            }
        }

        public string Cama
        {
            get { return m_cama; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for m_cama", value, value.ToString());

                m_isChanged |= (m_cama != value); m_cama = value;
            }
        }

        /// <summary>
        /// 0:Abierto; 1:En Proceso; 2:Cerrado; 
        /// </summary>
        public int Estado
        {
            get { return m_estado; }
            set
            {
                m_isChanged |= (m_estado != value);
                m_estado = value;
            }

        }

        /// <summary>
        /// 
        /// </summary>
        public bool Alerta
        {
            get { return m_alerta; }
            set
            {
                m_isChanged |= (m_alerta != value);
                m_alerta = value;
            }

        }
		/// <summary>
		/// 
		/// </summary>
        public bool Baja
        {
            get { return m_baja; }
            set
            {
                m_isChanged |= ( m_baja != value ); 
                m_baja = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public bool Impreso
        {
            get { return m_impreso; }
            set
            {
                m_isChanged |= (m_impreso != value);
                m_impreso = value;
            }

        }
			
		/// <summary>
		/// 
		/// </summary>
		public Usuario IdUsuarioRegistro
		{
			get { return m_idusuarioregistro; }
			set
			{
				m_isChanged |= ( m_idusuarioregistro != value ); 
				m_idusuarioregistro = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime FechaRegistro
		{
			get { return m_fecharegistro; }
			set
			{
				m_isChanged |= ( m_fecharegistro != value ); 
				m_fecharegistro = value;
			}

		}
        public int IdMuestra
        {
            get { return m_idmuestra; }
            set
            {
                m_isChanged |= (m_idmuestra != value);
                m_idmuestra = value;
            }
        }

        public DateTime FechaTomaMuestra
        {
            get { return m_fechatomamuestra; }
            set
            {
                m_isChanged |= (m_fechatomamuestra != value);
                m_fechatomamuestra = value;
            }

        }
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
		{
			get { return m_isChanged; }
		}
				

		#endregion 

        ///////////
        /// Metodos
        /// 
        public int GenerarNumero()
        {
            Configuracion oC = new Configuracion();
            oC = (Configuracion)oC.Get(typeof(Configuracion), 1);

            int numerito = 0;

            if (oC.UtilizaNumeroEliminado) /// si la configuracion admite reutiliza numeros dados de baja entra acá
            {
                ICriteria crit = m_session.CreateCriteria(typeof(Protocolo));
                ///1.busco todos los protocolos dados de baja
                crit.Add(Expression.Eq("Baja", true));
                IList lista = crit.List();
                if (lista.Count > 0)
                {
                    //recorro los protocolos dados de baja
                    foreach (Protocolo oP in lista)
                    {
                        //Verifico si para ese numero existe otro numero igual dado de alta
                        ICriteria crit2 = m_session.CreateCriteria(typeof(Protocolo));
                        crit2.Add(Expression.Eq("Numero", oP.Numero));
                        crit2.Add(Expression.Eq("Baja", false));
                        

                        IList lista2 = crit2.List();
                        if (lista2.Count == 0) ///se puede usar el numero dado de baja por que no tiene uno igual dado de alta
                        {
                            numerito = oP.Numero;
                            break;
                        }
                        /////ver si está anulado
                        //if (oP.Baja) //si está anulado se reutiliza el numero
                        //    numerito = oP.Numero;
                        //else
                        //    numerito = oP.Numero + 1;
                    }
                }

            }

            if (numerito == 0)
            {
                Protocolo oUltimoProtocolo = new Protocolo();
                ICriteria crit3 = m_session.CreateCriteria(typeof(Protocolo));
               
                //crit3.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo  order by Numero desc)"));
                crit3.Add(Expression.Sql(" IdProtocolo in (Select max (IdProtocolo) From LAb_Protocolo)"));
                oUltimoProtocolo =(Protocolo) crit3.UniqueResult();
                if (oUltimoProtocolo != null)
                    numerito = oUltimoProtocolo.Numero + 1;
                else
                    numerito = 1;                                   
            }

            return numerito;
        }


       
        public int GenerarNumeroDiario(string fecha)
        {
            Configuracion oC = new Configuracion();
            oC = (Configuracion)oC.Get(typeof(Configuracion), 1);

            int numerito = 0;
            
            if (oC.UtilizaNumeroEliminado) /// si la configuracion admite reutiliza numeros dados de baja entra acá
            {
                ICriteria crit = m_session.CreateCriteria(typeof(Protocolo));
                ///1.busco todos los protocolos dados de baja
                crit.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where Baja=1 and fecha='" + fecha + "' order by IdProtocolo )"));

                IList lista = crit.List();
                if (lista.Count > 0)
                {
                    //recorro los protocolos dados de baja
                    foreach (Protocolo oP in lista)
                    {
                        //Verifico si para ese numero existe otro numero igual dado de alta
                        ICriteria crit2 = m_session.CreateCriteria(typeof(Protocolo));
                        crit2.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where NumeroDiario=" + oP.NumeroDiario + " and Baja=0 and fecha='" + fecha + "' order by IdProtocolo )"));
                        IList lista2 = crit2.List();
                        if (lista2.Count == 0) ///se puede usar el numero dado de baja por que no tiene uno igual dado de alta
                        {
                            numerito = oP.NumeroDiario;
                            break;
                        }
                    }
                }
            }

            if (numerito == 0)
            {
                Protocolo oUltimoProtocolo = new Protocolo();
                ICriteria crit3 = m_session.CreateCriteria(typeof(Protocolo));
                crit3.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where Fecha='" + fecha + "' order by NumeroDiario desc)"));
                oUltimoProtocolo = (Protocolo)crit3.UniqueResult();
                if (oUltimoProtocolo != null)
                    numerito = oUltimoProtocolo.NumeroDiario + 1;
                else
                    numerito = 1;

            }

            return numerito;
        }

        public string GetNumero()
        {  
            Configuracion oC = new Configuracion();   oC = (Configuracion)oC.Get(typeof(Configuracion), 1);
            switch (oC.TipoNumeracionProtocolo )
            {
                case 0:  return this.Numero.ToString();
                case 1:  return this.NumeroDiario.ToString(); 
                case 2:  return this.PrefijoSector+ this.NumeroSector.ToString();
                default: return this.NumeroTipoServicio.ToString();
            }
        }

        public int GetResultadosPendientes()
        {
            int numerito = 0;
            //budsca los terminados pendientes de imprimir
            string m_strSQL = " SELECT COUNT(*) AS Cantidad FROM LAB_Protocolo WHERE  (estado < 2) AND (baja = 0)";

            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds);

            //conn.Close();
            //adapter.Dispose();
            if (Ds.Tables[0].Rows.Count > 0)
                numerito = int.Parse(Ds.Tables[0].Rows[0].ItemArray[0].ToString());

            return numerito;
        }

        public int GetPendientesImprimir()
        {
            int numerito = 0;
            //budsca los terminados pendientes de imprimir
            string m_strSQL = " SELECT COUNT(*) AS Cantidad FROM LAB_Protocolo WHERE (estado = 2) AND (impreso = 0) AND (baja = 0)";

            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds);

            //conn.Close();
            //adapter.Dispose();
            if (Ds.Tables[0].Rows.Count > 0)
               numerito= int.Parse( Ds.Tables[0].Rows[0].ItemArray[0].ToString());

            return numerito;
        }


        public int GetPendientesValidar()
        {
            int numerito = 0;
            //budsca los terminados pendientes de imprimir
            string m_strSQL = " SELECT COUNT(*) AS Cantidad FROM LAB_Protocolo WHERE (estado = 1) AND (baja = 0)";

            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds);

            //conn.Close();
            //adapter.Dispose();
            if (Ds.Tables[0].Rows.Count > 0)
                numerito = int.Parse(Ds.Tables[0].Rows[0].ItemArray[0].ToString());

            return numerito;
        }


        public DataTable GetDataSet(string tipo, string filtro, int tipoServicio)        
        {
            string m_strFiltro = filtro;
            Configuracion oCon = new Configuracion(); oCon = (Configuracion)oCon.Get(typeof(Configuracion), 1);
                     

            string m_strOrden=   "  ";
            if (tipo != "Resultados")
            {
                ///impresion de un protocolo
                 //if (tipoServicio == 1)  //LABORATORIO
                     m_strFiltro = "WHERE idProtocolo="+IdProtocolo.ToString();
                //else
                  //  m_strFiltro = IdProtocolo.ToString();

                m_strOrden = " ORDER BY  idDetalleProtocolo";
            }
            else
            {
                
                if (tipoServicio != 3) ///laboratorio o pesquisa 
                {
                    if (oCon.OrdenImpresionLaboratorio)
                        m_strOrden = " ORDER BY idProtocolo,idDetalleProtocolo";
                    else
                        m_strOrden = " ORDER BY idProtocolo, ordenArea, orden, orden1 ";
                }
                if (tipoServicio == 3)
                {
                    if (oCon.OrdenImpresionMicrobiologia)
                        m_strOrden = " ORDER BY idProtocolo,idDetalleProtocolo";
                    else
                        m_strOrden = " ORDER BY idProtocolo, ordenArea, orden, orden1 ";
                }
            }

            DataSet Ds = new DataSet();
               string m_strSQL = "";
               if (tipoServicio != 3)  //LABORATORIO o pesquisa
               {

                   //SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
                   //SqlCommand cmd = new SqlCommand();
                   //cmd.CommandType = CommandType.StoredProcedure;
                   //cmd.CommandText = "[LAB_ResultadoLaboratorio]";

                   //cmd.Parameters.Add("@Filtro", SqlDbType.VarChar);
                   //cmd.Parameters["@Filtro"].Value = m_strFiltro;

                   //cmd.Parameters.Add("@orden", SqlDbType.VarChar);
                   //cmd.Parameters["@orden"].Value = m_strOrden;


                   //cmd.Connection = conn;
                   //SqlDataAdapter da = new SqlDataAdapter(cmd);

                   //da.Fill(Ds, "resultado"); 

                   m_strSQL = " SELECT  idProtocolo, estado, codigo, orden, apellido, nombre, edad, fechaNacimiento, sexo, numeroDocumento, fecha, domicilio, HC, prioridad, origen, area, " +
                               "  grupo, item, resultadoCar, resultadoNum, observaciones, esTitulo, derivado, unidad, fechaEntrega, numero, hiv, metodo, valorReferencia, " +
                               "  idDetalleProtocolo, muestra, case when solicitante is null then 'No informado' else solicitante end as solicitante, conresultado, formatoDecimal,idTipoResultado, " +
                               " CONVERT(varchar(20), formato0) AS formato0, " +
                               "  CONVERT(varchar(20), formato1) AS formato1, " +
                               " CONVERT(varchar(20), formato2) AS formato2, " +
                               " CONVERT(varchar(20), formato3) AS formato3, " +
                               "  CONVERT(varchar(20), formato4) AS  formato4 , sector, sala, cama, firmante, embarazo , unidadEdad, observacionDetalle  " +
                               " FROM vta_LAB_ImprimirResultados " + m_strFiltro + m_strOrden;
                   //" WHERE idProtocolo=" + IdProtocolo +  m_strOrden ;

                //   DataSet Ds = new DataSet();
                   SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
                   SqlDataAdapter adapter = new SqlDataAdapter();
                   adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
                   adapter.Fill(Ds, "resultado");

               }
               if (tipoServicio == 3) ///MICROBIOLOGIA
               {
                  
                   SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
                   SqlCommand cmd = new SqlCommand();
                   cmd.CommandType = CommandType.StoredProcedure;
                   cmd.CommandText = "LAB_ResultadoMicrobiologia2";                  

                   cmd.Parameters.Add("@Filtro", SqlDbType.VarChar);
                   cmd.Parameters["@Filtro"].Value = m_strFiltro;
                                    

                   cmd.Connection = conn;                   
                   SqlDataAdapter da = new SqlDataAdapter(cmd);

                   da.Fill(Ds,"resultado");
         

               }              
        


            ///////Antibiograma
            // m_strSQL = @" SELECT   idProtocolo,  germen, antibiotico, resultado as resultado FROM vta_LAB_Antibiograma where idProtocolo = 32635 ORDER BY germen, antibiotico";
            ////DataSet Ds = new DataSet();
            ////SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            ////SqlDataAdapter adapter = new SqlDataAdapter();
            //adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            //adapter.Fill(Ds, "antibiograma");


            //conn.Close();
            //adapter.Dispose();
         //   return Ds.Tables[0];

            ///Le agrega al datatable la imagen
            ///
           
            DataTable data = Ds.Tables[0]; 
            if (tipo=="Resultados")
            {
                if (Ds.Tables[0].Rows.Count > 0)
                {
                    Configuracion oC = new Configuracion();
                    oC = (Configuracion)oC.Get(typeof(Configuracion), "IdConfiguracion", 1);
                    if (oC.RutaLogo != "")
                    {
                        string ImageFile = System.Web.HttpContext.Current.Request.MapPath("../Logo/" + oC.RutaLogo);
                        data.Columns.Add("img", System.Type.GetType("System.Byte[]"));

                        for (int i = 0; i < data.Rows.Count; i++)
                        {
                            FileStream fs = new FileStream(ImageFile, FileMode.Open);
                            BinaryReader br = new BinaryReader(fs);
                            data.Rows[i][35] = br.ReadBytes((int)br.BaseStream.Length);
                            br = null;
                            fs.Close();
                            fs = null;
                        }
                    }
                }
            }
            return data;


        }

        public DateTime CalcularCalendarioEntrega(DateTime fechaentrega)
        {
            int diaEntrega = (int)fechaentrega.DayOfWeek;
            bool seguirBuscando = true;
            DateTime fecha = fechaentrega;

            CalendarioEntrega oItem = new CalendarioEntrega();
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(CalendarioEntrega));
            crit.Add(Expression.Eq("IdEfector", this.IdEfector));
            int dif = 0;
            IList items = crit.List();
            foreach (CalendarioEntrega oDia in items)
            {
                if (oDia.Dia == diaEntrega) { fecha = fechaentrega; seguirBuscando = false; break; }
            }

            if (seguirBuscando)
                foreach (CalendarioEntrega oDia in items)
                {
                    if (diaEntrega < oDia.Dia) { dif = oDia.Dia - diaEntrega; fecha = fechaentrega.AddDays(dif); seguirBuscando = false; break; }
                }

            if (seguirBuscando)
                foreach (CalendarioEntrega oDia in items)
                {
                    if (diaEntrega > oDia.Dia) 
                    { 
                        dif = diaEntrega - oDia.Dia - 7;
                        if (dif < 0) dif = dif * (-1);
                        fecha = fechaentrega.AddDays(dif); break; 
                    }
                }

            return fecha;
        }

        public bool EnProceso()
        {
            bool enproceso = false;
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
            crit.Add(Expression.Eq("IdProtocolo", this));
            //crit.Add(Expression.Eq("IdEfector", this.IdEfector));
            

            IList detalle = crit.List();
            if (detalle.Count > 0)
            {
                foreach (DetalleProtocolo oDetalle in detalle)
                {

                    if (oDetalle.IdUsuarioResultado > 0)
                    {
                        enproceso = true;
                        break;
                    }
                    if (oDetalle.IdUsuarioControl > 0)
                    {
                        enproceso = true;
                        break;
                    }
                    if (oDetalle.IdUsuarioValida > 0)
                    {
                        enproceso = true;
                        break;
                    }
                    if (oDetalle.Enviado > 1)
                    {
                        enproceso = true;
                        break;
                    }
                }
            }
            return enproceso;
        }

        public void ActualizarResultados(string s_operacion, int i_idusuario)
        {
            ///Esta funcion pone como cargados los item del tipo compuestos.

            
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
            crit.Add(Expression.Eq("IdProtocolo", this));
            crit.Add(Expression.Eq("IdEfector", this.IdEfector));

            IList detalle = crit.List();
            if (detalle.Count > 0)
            {
                foreach (DetalleProtocolo oDet in detalle)
                {

                    if (oDet.IdSubItem.IdCategoria == 1) //revisar: si es compuesto y tiene hijos con resultados
                    {

                        if (HijosTieneResultado(oDet))
                        {
                            oDet.ConResultado = true;
                            if (s_operacion == "Carga")
                            {
                                oDet.IdUsuarioResultado = i_idusuario;
                                oDet.FechaResultado = DateTime.Now;
                            }
                            else
                            {
                                oDet.IdUsuarioValida = i_idusuario;
                                oDet.FechaValida = DateTime.Now;
                            }
                            oDet.Save();
                        }
                    }

                    if (oDet.IdSubItem.IdEfectorDerivacion != oDet.IdSubItem.IdEfector) //derivado
                    {


                        Derivacion oDeriva = new Derivacion();
                        oDeriva = (Derivacion)oDeriva.Get(typeof(Derivacion), "IdDetalleProtocolo", oDet);
                        if (oDeriva != null)  /// esta pendiente
                        {
                            if (oDeriva.Estado == 1) /// enviado
                                oDet.ResultadoCar = "Derivado: " + oDet.IdSubItem.IdEfectorDerivacion.Nombre;
                            if (oDeriva.Estado == 2) /// no enviado
                                oDet.ResultadoCar = " No Derivado. " + oDeriva.Observacion;

                        }
                        else { oDet.ResultadoCar = "Pendiente de derivar"; }

                            if (s_operacion == "Carga")
                            {
                                oDet.IdUsuarioResultado = i_idusuario;
                                oDet.FechaResultado = DateTime.Now;
                            }
                            else
                            {
                                oDet.IdUsuarioValida = i_idusuario;
                                oDet.FechaValida = DateTime.Now;
                            }
                            oDet.Save();
                        
                    }

                    
                }
            }
           
        }

        private bool HijosTieneResultado(DetalleProtocolo oDetalle)
        {
            bool hay = true;
            string conResultado = "";
            ///trae los hijos que tiene en detalle
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(PracticaDeterminacion));
            crit.Add(Expression.Eq("IdItemPractica", oDetalle.IdSubItem));
            //crit.Add(Expression.Eq("IdEfector", this.IdEfector));

            IList detalle = crit.List();
            if (detalle.Count > 0)
            {
                foreach (PracticaDeterminacion oHijo in detalle)
                {
                    hay = false;

                    string m_strSQL = " SELECT   CASE WHEN trajoMuestra = 'Si' THEN conresultado ELSE CAST(1 AS bit) END AS conResultado "+
                        " FROM LAB_DetalleProtocolo WHERE     idProtocolo =" + oDetalle.IdProtocolo.IdProtocolo.ToString() + " AND idSubItem = " + oHijo.IdItemDeterminacion.ToString();

            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds);

                    if (Ds.Tables[0].Rows.Count > 0)
                    conResultado = Ds.Tables[0].Rows[0].ItemArray[0].ToString();

                    if (conResultado == "True")
                    { hay = true; break; }
                }                
            }
            else
                hay = false;
            return hay;
        }


        public bool ValidadoTotal(string s_operacion, int i_idusuario)
        {
            bool validado = true;
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
            crit.Add(Expression.Eq("IdProtocolo", this));
            crit.Add(Expression.Eq("IdEfector", this.IdEfector));

            IList detalle = crit.List();
            if (detalle.Count > 0)
            {
                foreach (DetalleProtocolo oDetalle in detalle)
                {
                    if (oDetalle.IdUsuarioValida > 0)
                        validado = true;
                    else
                    {
                        if (oDetalle.IdSubItem.IdCategoria == 1) //compuesto
                            validado = true;
                        else
                        {
                            if (oDetalle.TrajoMuestra == "No") //sin muestra
                            {
                                validado = true;
                                if (s_operacion == "Carga")
                                {
                                    oDetalle.IdUsuarioResultado = i_idusuario;
                                    oDetalle.FechaResultado = DateTime.Now;
                                }
                                else
                                {
                                    oDetalle.IdUsuarioValida = i_idusuario;
                                    oDetalle.FechaValida = DateTime.Now;
                                }
                                oDetalle.Save();
                            }
                            else
                            {
                                if (oDetalle.IdSubItem.IdEfectorDerivacion != oDetalle.IdSubItem.IdEfector) //derivado
                                {


                                    //Derivacion oDeriva = new Derivacion();
                                    //oDeriva = (Derivacion)oDeriva.Get(typeof(Derivacion), "IdDetalleProtocolo", oDetalle);
                                    //if (oDeriva != null)  /// esta pendiente
                                    //{
                                    //    if (oDeriva.Estado == 1) /// enviado
                                    //        oDetalle.ResultadoCar = "Derivado: " + oDetalle.IdSubItem.IdEfectorDerivacion.Nombre;
                                    //    if (oDeriva.Estado == 2) /// no enviado
                                    //        oDetalle.ResultadoCar = " No Derivado. " + oDeriva.Observacion;

                                    //}
                                    //else
                                    //    oDetalle.ResultadoCar = " Pendiente de derivar " ;

                                    //    if (s_operacion == "Carga")
                                    //    {
                                    //        oDetalle.IdUsuarioResultado = i_idusuario;
                                    //        oDetalle.FechaResultado = DateTime.Now;
                                    //    }
                                    //    else
                                    //    {
                                    //        oDetalle.IdUsuarioValida = i_idusuario;
                                    //        oDetalle.FechaValida = DateTime.Now;
                                    //    }
                                    //    oDetalle.Save();
                                        validado = true;
                                    
                                }
                                else
                                {
                                    validado = false;
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            return validado;
        }



        public void CalcularFormulas(string s_operacion, int i_idusuario, bool solovacio)
        {
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
            crit.Add(Expression.Eq("IdProtocolo", this));
            crit.Add(Expression.Eq("IdEfector", this.IdEfector));
            crit.Add(Expression.Eq("TrajoMuestra", "Si"));
            
            if (solovacio)   // solo detalle sin resultados
            {
                crit.Add(Expression.Eq("ConResultado",false));
            }

            IList lista = crit.List();

           // string valor = "NA";
            //ISession m_session = NHibernateHttpModule.CurrentSession;
            //ICriteria crit = m_session.CreateCriteria(typeof(Formula));
            //crit.Add(Expression.Eq("IdItem", item));
            //crit.Add(Expression.Eq("IdEfector", item.IdEfector));
            //crit.Add(Expression.Eq("Baja", false));

            //IList lista = crit.List();
            if (lista.Count > 0)
            {
                foreach (DetalleProtocolo oDet in lista)
                {                   
                    ICriteria critFormula = m_session.CreateCriteria(typeof(Formula));
                    critFormula.Add(Expression.Eq("IdItem", oDet.IdSubItem));
                    critFormula.Add(Expression.Eq("IdTipoFormula", 1));
                    critFormula.Add(Expression.Eq("Baja", false));
                    IList lista2 = critFormula.List();
                    foreach (Formula oFormula in lista2)
                    {
                        bool sicalcula = false;
                        if ((oDet.IdProtocolo.Sexo == oFormula.Sexo) || (oFormula.Sexo == "I")) // coincide el sexo del paciente o el sexo del valor de referencia es Indistinto
                        {
                            int edadDesde = oFormula.EdadDesde;
                            int edadHasta = oFormula.EdadHasta;
                            int unidadEdad = oFormula.UnidadEdad;
                            if (unidadEdad == -1)
                                sicalcula = true;
                            else
                            {
                                if ((unidadEdad == oDet.IdProtocolo.UnidadEdad) && (edadDesde <= oDet.IdProtocolo.Edad) && (edadHasta >= oDet.IdProtocolo.Edad))
                                    sicalcula = true;
                            }
                        }

                        if (sicalcula)
                        {
                            string formulacalculada = oFormula.ContenidoFormula;
                            string aux = oFormula.ContenidoFormula.Replace("+", ";");
                            aux = aux.Replace("-", ";");
                            aux = aux.Replace("/", ";");
                            aux = aux.Replace("\\", ";");
                            aux = aux.Replace("*", ";");
                            aux = aux.Replace("(", ";");
                            aux = aux.Replace(")", ";");
                            aux = aux.Replace("!", ";");
                            aux = aux.Replace("^", ";");
                            aux = aux.ToLower().Replace("mod", ";");
                            aux = aux.ToLower().Replace("min", ";");
                            aux = aux.ToLower().Replace("max", ";");
                            aux = aux.ToLower().Replace("sin", ";");
                            aux = aux.ToLower().Replace("cos", ";");
                            aux = aux.ToLower().Replace("tan", ";");
                            aux = aux.ToLower().Replace("atan", ";");
                            aux = aux.ToLower().Replace("abs", ";");
                            aux = aux.ToLower().Replace("log", ";");
                            aux = aux.ToLower().Replace("ceil", ";");
                            aux = aux.ToLower().Replace("int", ";");
                            aux = aux.ToLower().Replace("frac", ";");
                            aux = aux.ToLower().Replace("sqr", ";");


                            string[] arr = aux.Split((";").ToCharArray());
                            foreach (string m in arr)
                            {
                                if (m.Length > 0)
                                {
                                    if (m.Substring(0, 1) == "[")
                                    {
                                        string codigoDet = m.Replace("[", "");
                                        codigoDet = codigoDet.Replace("]", "");
                                        decimal valorEncontrado = 0;
                                        if (codigoDet.ToUpper() == "EDAD")
                                            valorEncontrado = decimal.Parse(this.Edad.ToString());
                                        else

                                            valorEncontrado = BuscarResultadoItemenBase(codigoDet);
                                        if (valorEncontrado == -99999) break;
                                        else
                                        {
                                            formulacalculada = formulacalculada.Replace("[" + codigoDet.ToUpper() + "]", valorEncontrado.ToString());
                                            formulacalculada = formulacalculada.Replace(".", ","); ///reemplazo puntos por comas en los numeros decimales; para aplicar la funcion Evaluate.                                                                                                                       
                                        }
                                    }
                                }
                                //else
                                //    formulacalculada = m;

                            }

                            //      valor =System.Web.UI.s formulacalculada.

                            Parser p = new Parser();
                            double resultado = 0;
                            if (p.Evaluate(formulacalculada))
                            {
                                resultado = p.Result;

                                oDet.ResultadoNum = Math.Round(decimal.Parse(resultado.ToString()), oDet.IdSubItem.FormatoDecimal);
                                oDet.ConResultado = true;

                                if (s_operacion == "Carga")
                                {
                                    if (oDet.ConResultado)
                                    {
                                        oDet.IdUsuarioResultado = i_idusuario;
                                        oDet.FechaResultado = DateTime.Now;
                                    }
                                }
                                else
                                {
                                    oDet.IdUsuarioValida = i_idusuario;
                                    oDet.FechaValida = DateTime.Now;
                                }
                                oDet.Save();
                            }
                        }
                    
                        //valor = resultado.ToString();
                    }
                }
            }
            //return valor;


            //string valorFormula= GetValorFormula(oDetalle.IdSubItem);
            //if (valorFormula!="NA")
            //oDetalle.ResultadoNum = decimal.Parse( valorFormula);

        }


        private decimal BuscarResultadoItemenBase(string codigoDet)
        {
            Utility oUtil= new Utility();
            decimal valor = 0;
            Item oItem = new Item();
            oItem = (Item)oItem.Get(typeof(Item), "Codigo", codigoDet,"Baja",false);
            if (oItem != null)
            {
                if (oItem.IdTipoResultado == 1)
                {
                    ISession m_session = NHibernateHttpModule.CurrentSession;
                    ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
                    crit.Add(Expression.Eq("IdProtocolo", this));
                    crit.Add(Expression.Eq("IdEfector", this.IdEfector));
                    crit.Add(Expression.Eq("IdSubItem", oItem));              

                    DetalleProtocolo odet = (DetalleProtocolo)crit.UniqueResult();
                    if (odet != null)
                    {
                        if (odet.ConResultado)
                        {
                            if (odet.IdSubItem.IdTipoResultado == 2)/// texto
                            {
                                if (oUtil.EsNumerico(odet.ResultadoCar)) valor = decimal.Parse(odet.ResultadoCar);
                            }
                            if (odet.IdSubItem.IdTipoResultado == 1)/// numerico
                                valor = odet.ResultadoNum;
                        }
                        else
                            valor = -99999;
                    }
                    else valor = -99999;
                }
            }
            else valor = -99999;
            return valor;
        }

        public int GenerarNumeroGrupo(SectorServicio oSector)
        {
            Configuracion oC = new Configuracion();
            oC = (Configuracion)oC.Get(typeof(Configuracion), 1);
            int numerito = 0;

            if (oC.UtilizaNumeroEliminado) /// si la configuracion admite reutiliza numeros dados de baja entra acá
            {
                ICriteria crit = m_session.CreateCriteria(typeof(Protocolo));
                ///1.busco todos los protocolos dados de baja
                crit.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where Baja=1 and idSector=" + oSector.IdSectorServicio.ToString() + " order by IdProtocolo )"));

                IList lista = crit.List();
                if (lista.Count > 0)
                {
                    //recorro los protocolos dados de baja
                    foreach (Protocolo oP in lista)
                    {
                        //Verifico si para ese numero existe otro numero igual dado de alta
                        ICriteria crit2 = m_session.CreateCriteria(typeof(Protocolo));
                        crit2.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where NumeroSector=" + oP.NumeroSector + " and Baja=0 and idSector=" + oSector.IdSectorServicio.ToString() + " order by IdProtocolo )"));
                        IList lista2 = crit2.List();
                        if (lista2.Count == 0) ///se puede usar el numero dado de baja por que no tiene uno igual dado de alta
                        {
                            numerito = oP.NumeroSector;
                            break;
                        }
                    }
                }
            }

            if (numerito == 0)
            {
                Protocolo oUltimoProtocolo = new Protocolo();
                ICriteria crit3 = m_session.CreateCriteria(typeof(Protocolo));
                crit3.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where idSector=" + oSector.IdSectorServicio.ToString() + " order by NumeroSector desc)"));
                oUltimoProtocolo = (Protocolo)crit3.UniqueResult();
                if (oUltimoProtocolo != null)
                    numerito = oUltimoProtocolo.NumeroSector + 1;
                else
                    numerito = 1;
            }

            return numerito;

        }


        public int GenerarNumeroTipoServicio(TipoServicio oServicio)
        {
            Configuracion oC = new Configuracion();
            oC = (Configuracion)oC.Get(typeof(Configuracion), 1);
            int numerito = 0;

            if (oC.UtilizaNumeroEliminado) /// si la configuracion admite reutiliza numeros dados de baja entra acá
            {
                ICriteria crit = m_session.CreateCriteria(typeof(Protocolo));
                ///1.busco todos los protocolos dados de baja
                crit.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where Baja=1 and idTipoServicio=" + oServicio.IdTipoServicio.ToString() + " order by IdProtocolo )"));

                IList lista = crit.List();
                if (lista.Count > 0)
                {
                    //recorro los protocolos dados de baja
                    foreach (Protocolo oP in lista)
                    {
                        //Verifico si para ese numero existe otro numero igual dado de alta
                        ICriteria crit2 = m_session.CreateCriteria(typeof(Protocolo));
                        crit2.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where NumeroTipoServicio=" + oP.NumeroTipoServicio + " and Baja=0 and IdTipoServicio=" +oServicio.IdTipoServicio.ToString() + " order by IdProtocolo )"));
                        IList lista2 = crit2.List();
                        if (lista2.Count == 0) ///se puede usar el numero dado de baja por que no tiene uno igual dado de alta
                        {
                            numerito = oP.NumeroTipoServicio;
                            break;
                        }
                    }
                }
            }

            if (numerito == 0)
            {
                Protocolo oUltimoProtocolo = new Protocolo();
                ICriteria crit3 = m_session.CreateCriteria(typeof(Protocolo));
                crit3.Add(Expression.Sql(" IdProtocolo in (Select top 1 IdProtocolo From LAb_Protocolo where IdTipoServicio=" + oServicio.IdTipoServicio.ToString() + " order by NumeroTipoServicio desc)"));
                oUltimoProtocolo = (Protocolo)crit3.UniqueResult();
                if (oUltimoProtocolo != null)
                    numerito = oUltimoProtocolo.NumeroTipoServicio + 1;
                else
                    numerito = 1;
            }

            return numerito;

        }

        public object GetDataSetCodigoBarras(string p, string s_listaAreas, int tipoServicio, bool adicionalGeneral)        
        {            
         
            string m_strSQL = @" SELECT [idProtocolo]      ,[idArea]      ,[numeroP]      ,[area]
            ,[Fecha]      ,[Origen]      ,[Sector]      ,[NumeroOrigen]      ,[NumeroDocumento]      ,[apellido]      ,[Sexo]      ,[edad],pacientecodificado
            FROM vta_LAB_GeneraCodigoBarras
            WHERE    (idArea IN (" + s_listaAreas + ")) AND idProtocolo =" + this.IdProtocolo.ToString();

            if (adicionalGeneral)
            {
                m_strSQL += @" UNION 
                SELECT [idProtocolo]      ,[idArea]      ,[numeroP]      ,[area]
                ,[Fecha]      ,[Origen]      ,[Sector]      ,[NumeroOrigen]      ,[NumeroDocumento]      ,[apellido]      ,[Sexo]      ,[edad], pacientecodificado
                FROM vta_LAB_GeneraCodigoBarrasGeneral                    
                WHERE    idProtocolo =" + this.IdProtocolo.ToString();
            }

            m_strSQL += " ORDER BY idArea";

            
            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds, "resultado");

            
            DataTable data = Ds.Tables[0];
            return data;
        }


        public void GrabarAuditoriaProtocolo(string m_accion, int m_idusuario)
        {
            AuditoriaProtocolo oRegistro = new AuditoriaProtocolo();
            oRegistro.Accion = m_accion;
            oRegistro.Fecha = DateTime.Now;
            oRegistro.Hora = DateTime.Now.ToLongTimeString();
            oRegistro.IdProtocolo = this.IdProtocolo;
            oRegistro.IdUsuario = m_idusuario;
            oRegistro.Save();
        }

        public void GrabarAuditoriaDetalleProtocolo(string m_accion, int m_idusuario,string m_observacion, string m_resultado)
        {
            AuditoriaProtocolo oRegistro = new AuditoriaProtocolo();
            oRegistro.Accion = m_accion;
            oRegistro.Analisis = m_observacion;
            oRegistro.Valor = m_resultado;
            oRegistro.Fecha = DateTime.Now;
            oRegistro.Hora = DateTime.Now.ToLongTimeString();
            oRegistro.IdProtocolo = this.IdProtocolo;
            oRegistro.IdUsuario = m_idusuario;
            oRegistro.Save();
        }

        public object GetDataSetAuditoria()
        {
            string m_strSQL = @" SELECT     dbo.NumeroProtocolo(A.idProtocolo) AS numero, U.username, CONVERT(varchar(10), A.fecha, 103) AS fecha, A.hora, A.accion, A.analisis, A.valor, A.valorAnterior
FROM         LAB_AuditoriaProtocolo AS A INNER JOIN
                      Sys_Usuario AS U ON A.idUsuario = U.idUsuario
where idprotocolo=" + this.IdProtocolo.ToString()+
" ORDER BY A.idAuditoriaProtocolo";       

            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = new SqlCommand(m_strSQL, conn);
            adapter.Fill(Ds, "auditoria");

            DataTable data = Ds.Tables[0];
            return data;
        }

        public string GetPracticasPedidas()
        {
            string s_practicas = "";
            DetalleProtocolo oDetalle = new DetalleProtocolo();
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(DetalleProtocolo));
            crit.Add(Expression.Eq("IdProtocolo", this));
            crit.AddOrder(Order.Asc("IdDetalleProtocolo"));

            IList items = crit.List();
            string pivot = "";
            string sDatos = "";
            foreach (DetalleProtocolo oDet in items)
            {
                if (pivot != oDet.IdItem.Nombre)
                {
                    if (sDatos == "")
                        sDatos = oDet.IdItem.Nombre;
                    else
                        sDatos += " - " + oDet.IdItem.Nombre;
                    //sDatos += "#" + oDet.IdItem.Codigo + "#" + oDet.IdItem.Nombre + "#" + oDet.TrajoMuestra + "@";                   
                    pivot = oDet.IdItem.Nombre;
                }

            }

            s_practicas = sDatos;
            return s_practicas;
        }

        public void VerificarExisteNumeroAsignado()
        {
            ICriteria crit2 = m_session.CreateCriteria(typeof(Protocolo));
            crit2.Add(Expression.Eq("Numero",this.Numero));
            crit2.Add(Expression.Eq("Baja", false));

            IList lista2 = crit2.List();
         
            foreach (Protocolo oP in lista2)
            {
                if (oP!=this)
                {   
                    this.Numero = this.GenerarNumero();
                    this.Save();
                }
            }
         
            
        }

        public DataTable GetDataSetComprobante()
        {
            DataSet Ds = new DataSet();
            SqlConnection conn = (SqlConnection)NHibernateHttpModule.CurrentSession.Connection;
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;


            cmd.CommandText = "[LAB_ListaProtocolo]";

            cmd.Parameters.Add("@FiltroBusqueda", SqlDbType.NVarChar);
            cmd.Parameters["@FiltroBusqueda"].Value = " P.idProtocolo= " + this.IdProtocolo.ToString();

            cmd.Parameters.Add("@TipoLista", SqlDbType.Int);
            cmd.Parameters["@TipoLista"].Value = "2";

            cmd.Parameters.Add("@idArea", SqlDbType.Int);
            cmd.Parameters["@idArea"].Value = "0";

            cmd.Parameters.Add("@idItem", SqlDbType.Int);
            cmd.Parameters["@idItem"].Value = "0";

            cmd.Connection = conn;


            SqlDataAdapter da = new SqlDataAdapter(cmd);

            da.Fill(Ds);
            //////////

            DataTable data = Ds.Tables[0]; 
            
            return data;
        }

        public string GetDiagnostico()
        {
            string diag = "";
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(ProtocoloDiagnostico));
            crit.Add(Expression.Eq("IdProtocolo", this));
            IList lista = crit.List();
            if (lista.Count > 0)
            {
                foreach (ProtocoloDiagnostico oDiag in lista)
                {
                    Cie10 oD = new Cie10();
                    oD = (Cie10)oD.Get(typeof(Cie10), oDiag.IdDiagnostico);
                    
                    if (diag == "") diag = oD.Nombre;
                    else diag += " - " + oD.Nombre;

                    //if (oD.Codigo == "Z32.1") diag += " Embarazada";
                }
            }
            return diag;
        }

        public string getCodificaHiv(string embarazada)
        {
            string nombre = this.IdPaciente.Nombre;
            string apellido = this.IdPaciente.Apellido;
            if (nombre.Length >= 2) nombre = nombre.Substring(0, 2);
            else   nombre = nombre + " ";

            if (apellido.Length >= 2)  apellido = apellido.Substring(0, 2);
            else  apellido = apellido + " ";

            string codigo=this.Sexo +  nombre + apellido+  this.IdPaciente.FechaNacimiento.ToShortDateString().Replace("/", "") + embarazada;
            return codigo.ToUpper();

        }

        public void GuardarWhonet( bool guardar)
        {
            ProtocoloWhonet oRegistro = new ProtocoloWhonet();
            oRegistro = (ProtocoloWhonet)oRegistro.Get(typeof(ProtocoloWhonet), "IdProtocolo", this);
            if (guardar)
            {
                if (oRegistro == null)
                {
                    ProtocoloWhonet oRegistroNew = new ProtocoloWhonet();
                    oRegistroNew.IdProtocolo = this;
                    oRegistroNew.Save();
                }
            }
            else
            {
                if (oRegistro != null) oRegistro.Delete();
            }
        }




        public string getDatosParentesco()
        {
            string s_paciente = "";
            SolicitudScreening oSolicitud = new SolicitudScreening();
            oSolicitud = (SolicitudScreening)oSolicitud.Get(typeof(SolicitudScreening), "IdProtocolo", this);
            if (oSolicitud!=null)
                //s_paciente = oSolicitud.ApellidoMaterno.ToUpper() + " " + oSolicitud.ApellidoPaterno.ToUpper() + " " + this.IdPaciente.Nombre.ToUpper();
                s_paciente = oSolicitud.ApellidoPaterno.ToUpper() + " " + this.IdPaciente.Nombre.ToUpper();
            return s_paciente;
        }

        public int getIncidencias()
        {
            ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(ProtocoloIncidenciaCalidad));
            crit.Add(Expression.Eq("IdProtocolo", this.IdProtocolo));
            IList lista = crit.List();
           return lista.Count ;
            
         
        }


        public void ValidarTodoslosAtb(int item, int usuario, bool completo)
        {
           ISession m_session = NHibernateHttpModule.CurrentSession;
            ICriteria crit = m_session.CreateCriteria(typeof(Antibiograma));
            crit.Add(Expression.Eq("IdProtocolo", this));
            crit.Add(Expression.Eq("IdItem", item));


            IList lista = crit.List();
            foreach (Antibiograma oAtb in lista)
            {
                if (completo)
                {
                    oAtb.FechaValida = DateTime.Now;
                    oAtb.IdUsuarioValida = usuario;
                    if (oAtb.Valor != "") oAtb.ValidaValor = true;
                    oAtb.Save();
                    this.GrabarAuditoriaDetalleProtocolo("Valida", oAtb.IdUsuarioValida, "ATB " + oAtb.NumeroAislamiento.ToString() + " " + oAtb.IdGermen.Nombre + " (" + oAtb.IdMetodologia.ToString() + ") - " + oAtb.IdAntibiotico.Descripcion, oAtb.Resultado);
                }
                else
                {
                    if  (oAtb.IdUsuarioValida==0)
                    {
                        oAtb.FechaValida = DateTime.Now;
                        oAtb.IdUsuarioValida = usuario;
                        if (oAtb.Valor != "") oAtb.ValidaValor = true;
                        oAtb.Save();
                        this.GrabarAuditoriaDetalleProtocolo("Valida", oAtb.IdUsuarioValida, "ATB " + oAtb.NumeroAislamiento.ToString() + " " + oAtb.IdGermen.Nombre + " (" + oAtb.IdMetodologia.ToString() + ") - " + oAtb.IdAntibiotico.Descripcion, oAtb.Resultado);
                    }
                }
                
            }
            
        }
    }
}
