/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class SolicitudScreeningAlarma: Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

        private int m_idsolicitudscreeningalarma;
        private SolicitudScreening m_idsolicitudscreening; 				
		private string m_descripcion; 
		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public SolicitudScreeningAlarma()
		{
            
			m_idsolicitudscreening = new SolicitudScreening();            
            m_descripcion = String.Empty; 
			
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public SolicitudScreeningAlarma(						
            SolicitudScreening idsolicitudscreening,
			string descripcion)
			: this()
		{

            m_idsolicitudscreening = idsolicitudscreening;			
			m_descripcion = descripcion;
			
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties			
	
		public int IdSolicitudScreeningAlarma
		{
			get { return m_idsolicitudscreeningalarma; }
			set
			{
                m_isChanged |= (m_idsolicitudscreeningalarma != value);
                m_idsolicitudscreeningalarma = value;
			}
		}

        public SolicitudScreening IdSolicitudScreening
        {
            get { return m_idsolicitudscreening; }
            set
            {
                m_isChanged |= (m_idsolicitudscreening != value);
                m_idsolicitudscreening = value;
            }
        }		
	
        public String Descripcion
        {
            get { return m_descripcion; }
            set
            {
                m_isChanged |= (m_descripcion != value);
                m_descripcion = value;
            }
        }		
      
		
        /// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
